### ISSUE TITLE
Folders with changes, modified should override untracked/ignored

### ISSUE THREAD

**Issue by rafi** [lambdalisue/fern-git-status.vim#1]
Folders with **modified** and **untracked/ignored** files should show 'modified' symbol on folder. modified > untracked/ignored

Screenshot (defx on the left, fern on the right):
![image](https://user-images.githubusercontent.com/147918/89032439-56be4f80-d33d-11ea-9175-f192156856c2.png)

**Comment by lambdalisue** [comment]
1. It's technically difficult to determine the status of the directory from its children (with good performance)
2. It's ambiguous and no obious rules exists while there is [more statuses](https://github.com/lambdalisue/fern-git.vim/blob/master/autoload/fern_git/grantor.vim#L11-L18)

Thus what you've mention is correct behavior at least for now.

So the options are

1. Provide me clear rules to determine the directory status from combinations of children status
    - But I'm not sure if I can solve the performance issue
2. Always use *modified* when one of children status has set
3. Else

**Comment by lambdalisue** [comment]
I decided to provide "Stained" and "Cleaned" status on directories.

I tried 1. first but faced on a performance issue thus I ended up.

**Comment by rafi** [comment]
I see, performance is really important.
