### ISSUE TITLE
Custom styling instead of `[!!]`, `[ M]`, `[??]`, `[--]`

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern-git-status.vim#6]
Hello,

By default *fern-git-status* will emit `git status` type details, two characters inside square bracket taking up four spaces.

That is fine as a default.

But, I would like to use just a single Unicode character such as `●` or `✖` to indicate dirty state. I don't want `[ M]` in my file tree.

The `g:fern_git_status#indexed_character` and ` g:fern_git_status#stained_character` flags are good, but they take up four spaces since square bracket and space will surround those characters. Single character symbol is my aim.

Is that possible now? If not, then I would request it as an enhancement request.

Many thanks, you are doing great work.

**Comment by bluz71** [comment]
This @rafi screenshoot [here](https://github.com/lambdalisue/fern-git-status.vim/issues/1#issue-669737675) is interesting (defx on left, fern on the right):

![](https://user-images.githubusercontent.com/147918/89032439-56be4f80-d33d-11ea-9175-f192156856c2.png)

Fern badges are taking up one space, I like the look. I also like the dots in defx left side. I want to replicate that look.

Best regards.

**Comment by lambdalisue** [comment]
Unfortunately no.

1. Remapping from a git status to a status indicator cost a bit. Remember, the Vim script is slow.
2. There is no **reasonable** mapping from a git status to a status indicator. Some want only `[ M]` as `dirty` but others want `[MM]` as `dirty` as well

Thus I don't think adding complexity for that feature pays the cost for that.

**Comment by bluz71** [comment]
Ok, that makes sense.

**Comment by bluz71** [comment]
Actually I am now quite happy with the looks, here is my *fern-with-status* setup:

<img width="780" alt="fern-git-status" src="https://user-images.githubusercontent.com/11382509/90326528-8c656880-dfcc-11ea-9ef7-881ff6391c6e.png">

Green - staged changes
Red - dirty state

**Comment by jonescamilla** [comment]
Would there be a way to remove the braces `[]` and have just the letters/symbols?

**Comment by lambdalisue** [comment]
@jonescamilla 

Unfortunately, it's hard coded. https://github.com/lambdalisue/fern-git-status.vim/blob/master/autoload/fern_git_status.vim#L59
