### ISSUE TITLE
Performance tip: recommend `git config feature.manyFiles true` for large repositories

### ISSUE THREAD

**Issue by bluz71** [lambdalisue/fern-git-status.vim#7]
Hello,

*fern-git-status* has a [performance](https://github.com/lambdalisue/fern-git-status.vim#performance) section in the front page README. That is helpful.

I suggest the following addition which really does help for Linux Kernel sized repositories:

> For large repositories it is also recommended to enable the [Git (2.24+) `manyFiles` feature](https://github.blog/2019-11-03-highlights-from-git-2-24/):
>
> ```sh
> git config feature.manyFiles true
> ```

**Comment by lambdalisue** [comment]
I didn't know that thanks 👍

**Comment by bluz71** [comment]
This Git enhancement was done by Microsoft about a year ago in this commit:

https://github.com/git/git/commit/c6cc4c5afd2efd5f8081a3839b48d003de4e094f

It really does help `git status` performance in big repositories. Hence it also helps fern as well. Best to let fern-git-status users know about this.

**Comment by bluz71** [comment]
@lambdalisue,

Do you want me to do create a PR?

If so, I will create one tomorrow.

**Comment by lambdalisue** [comment]
That's awesome! Yes, please.
